language: node_js
node_js:
  - '4.2'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - 'npm install -g gulp-cli webpack'
  - 'npm install'
script:
  - npm test
before_deploy: 
  - chmod a+x deploy.sh  
  - ./deploy.sh
  - ls | grep -v 'dist' | xargs rm -rf
  - cd dist
  - mv * ..
  - cd ..
  - rm -rf dist 
deploy:
  provider: heroku
  skip_cleanup: true  
  api_key:
    development:   
      secure: "mUfSgjTy+ATLt7izpaQDJjIyEE02kGP9j9MmVROBt9HavEDk3UrAixWEO+eFB7rTkXCcMXqkg5FaobWROJI9NHq+JS3DHuLYhix3pib8HZ7YdCKG0hxdGeufVs3Zf/hyCD1J/reDKcnOi4sguPNrYmhRJcLmTr1dkJP6V5QJ2EU="
    master:
      secure: "mUfSgjTy+ATLt7izpaQDJjIyEE02kGP9j9MmVROBt9HavEDk3UrAixWEO+eFB7rTkXCcMXqkg5FaobWROJI9NHq+JS3DHuLYhix3pib8HZ7YdCKG0hxdGeufVs3Zf/hyCD1J/reDKcnOi4sguPNrYmhRJcLmTr1dkJP6V5QJ2EU="
  app:
    development: alumni-db-frontend-dev
    master: alumni-db-frontend