language: node_js
node_js:
  - '4.2'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install --no-interactive'
  - 'npm install'
script:
  - grunt test
before_deploy: 
  - ./deploy_test.sh
deploy:
  provider: heroku
  api_key:
    development:   
      secure: "mUfSgjTy+ATLt7izpaQDJjIyEE02kGP9j9MmVROBt9HavEDk3UrAixWEO+eFB7rTkXCcMXqkg5FaobWROJI9NHq+JS3DHuLYhix3pib8HZ7YdCKG0hxdGeufVs3Zf/hyCD1J/reDKcnOi4sguPNrYmhRJcLmTr1dkJP6V5QJ2EU="
    master:
      secure: "mUfSgjTy+ATLt7izpaQDJjIyEE02kGP9j9MmVROBt9HavEDk3UrAixWEO+eFB7rTkXCcMXqkg5FaobWROJI9NHq+JS3DHuLYhix3pib8HZ7YdCKG0hxdGeufVs3Zf/hyCD1J/reDKcnOi4sguPNrYmhRJcLmTr1dkJP6V5QJ2EU="
  app:
    development: alumni-db-frontend-dev
    master: alumni-db-frontend
